-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_OUTS AS O
        LEFT JOIN ANIMAL_INS AS I ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE I.DATETIME IS NOT NULL
    ORDER BY O.DATETIME - I.DATETIME DESC
    LIMIT 2
    