-- 코드를 입력하세요
SELECT MONTH(ORIGIN.START_DATE), ORIGIN.CAR_ID, COUNT(ORIGIN.HISTORY_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ORIGIN
        INNER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                    GROUP BY CAR_ID HAVING COUNT(*) >= 5) AS SUB
        ON ORIGIN.CAR_ID = SUB.CAR_ID
    WHERE ORIGIN.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 1, 2
    ORDER BY MONTH(START_DATE), CAR_ID DESC
    
# SELECT MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#     WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
#     GROUP BY MONTH, CAR_ID
#         HAVING COUNT(HISTORY_ID) >= 5
#     ORDER BY MONTH(START_DATE), CAR_ID DESC