-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
    FROM ICECREAM_INFO AS INFO
        JOIN FIRST_HALF AS FH ON FH.FLAVOR = INFO.FLAVOR
    GROUP BY INFO.INGREDIENT_TYPE
    ORDER BY 2